# Define your experiments here. You can use the following as an example:
#
technical_debt:
  path: ".."
  query_api: True
  model_name: Base_29nov
  config_file: input/mvp.py
  timestep_hours: 0.25
  force_uncached: false
  show_progress: false
  parallelize: true
  log_exceptions: false
  use_datamodel: true
  inputs:
    - anylogic_key: P actors config JSON
      file: actors
    - anylogic_key: P grid connection config JSON
      file: gridconnections
    - anylogic_key: P grid node config JSON
      file: gridnodes
    - anylogic_key: P policies config JSON
      file: policies

  outcomes:
    - anylogic_key: O output runSettings
      human_key: APIOutputRunData
      writeExcel: False
      writeJSON: False
      print: False
    - anylogic_key: O total cost data
      human_key: APIOutputTotalCostData
      writeExcel: False
      writeJSON: False
      print: False
