version: "3.1"
services:
  web:
    image: nginx:alpine
    working_dir: /app
    ports:
      - "8000:80"
      - "8082:443"
    depends_on:
      - python
    volumes:
      - "./docker/files/static/502.html:/app/502.html:cached"
      - "./docker/files/config/nginx.conf.template:/etc/nginx/templates/default.conf.template:cached"
      - "./docker/files/certs:/etc/nginx/certs"
      - "./src/media:/app/media"
      - "./src/static:/app/static"
    environment:
      - PYTHON_HOST=http://python
      - NEXT_HOST=http://next
      - MEDIA_REMOTE_DOMAIN=holontool.nl
    extra_hosts:
      - "host.docker.internal:host-gateway"

  next:
    image: holon_nextjs
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/frontend/node_modules
      - /usr/src/frontend/.next
    depends_on:
      - web

  python:
    image: holon_wagtail_python
    build: ./src
    volumes:
      - "./src:/app"
    depends_on:
      - db
    env_file: ./docker/config/python.env

  db:
    image: postgis/postgis:12-2.5-alpine
    ports:
      - "8083:5432"
    volumes:
      - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
      - "./docker/files/shared:/shared:rw"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
