version: "3.1"
services:
  web:
    image: nginx:alpine
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - python
    volumes:
      - "./docker/files/static/502.html:/app/502.html"
      - "./docker/files/config/nginx.pizza.conf:/etc/nginx/templates/default.conf.template"
      - "./docker/files/certs:/etc/nginx/certs"
    environment:
      - PYTHON_HOST=http://python
      - NEXT_HOST=http://next
      - SERVER_NAME=pizzaoven.holontool.nl
    extra_hosts:
      - "host.docker.internal:host-gateway"

  next:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - web
    environment:
      - NEXT_PUBLIC_WAGTAIL_API_URL=https://pizzaoven.holontool.nl/wt/api/nextjs
      - NEXT_PUBLIC_BASE_URL=https://pizzaoven.holontool.nl/wt

  python:
    image: python_fakie_09
    build: 
      context: ./src
      dockerfile: Dockerfile.prod
    volumes:
      - "./src:/app"
    depends_on:
      - db
    env_file: ./docker/config/python.env

  db:
    image: prod_db
    build:
      context: ./db
    ports:
      - "8083:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
