version: "3.1"
services:
  web:
    image: holonregistry.azurecr.io/nginx:production
    build:
      context: ./docker
    ports:
      - "80:80"
    depends_on:
      - python
    volumes:
      - media-files:/app/media
      - static-files:/app/static
    environment:
      - PYTHON_HOST=http://python
      - NEXT_HOST=http://next
      - MEDIA_REMOTE_DOMAIN=holontool.nl
    extra_hosts:
      - "host.docker.internal:host-gateway"

  next:
    image: holonregistry.azurecr.io/nextjs:production
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - WAGTAIL_API_URL=http://python:8000/wt/api/nextjs
    expose:
      - 3000
    depends_on:
      - web

  python:
    image: holonregistry.azurecr.io/wagtail:production
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    environment:
      - DB_NAME=holon-wagtail-v2
      - DB_USER=holonadmin
      - DB_PASSWORD=UJ6ZkYQKqbz9LYd
      - DB_HOST=holon-webapp-database.postgres.database.azure.com
      - AZURE_ACCOUNT_NAME=holonstorage
      - AZURE_STORAGE_KEY=key
      - SECRET_KEY=cnkvmll4^-u*9jwc4gks&pfv(ws@4bw-y)ac0!=f-%b8ps3l3q
      - ALLOWED_HOSTS=*
      - DOMAIN_HOST=http://localhost
    ports:
      - 8000:8000
    volumes:
      - static-files:/home/app/web/static

volumes:
  static-files:
    # driver: azure_file
    # driver_opts:
    #   share_name: holon-webapp-static-files
    #   storage_account_name: holonstorage

  media-files:
    # driver: azure_file
    # driver_opts:
    #   share_name: holon-webapp-media-files
    #   storage_account_name: holonstorage
