version: "3.1"
services:
  web:
    image: holonregistry.azurecr.io/nginx:production
    ports:
      - "80:80"
    depends_on:
      - python
    environment:
      - PYTHON_HOST=http://python
      - NEXT_HOST=http://next
      - MEDIA_REMOTE_DOMAIN=holontool.nl
    extra_hosts:
      - "host.docker.internal:host-gateway"

  next:
    image: holonregistry.azurecr.io/nextjs:production
    expose:
      - 3000
    depends_on:
      - web

  python:
    image: holonregistry.azurecr.io/wagtail:production
    expose:
      - 8000
