name: Django CI

on:
  push:
    branches: ["main", "deployment"]
  pull_request:
    branches: ["main", "deployment"]

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost # default host value for the database
      DB_NAME: djtesting
      DB_PORT: 5432
      AL_API_KEY: test-api-key
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
          cd holon/services
          cloudclient_init -tf . --get-api-key
      - name: Lint with Black
        uses: psf/black@stable
        with:
          options: --check --line-length 100 --exclude "^.*\b(migrations)\b.*$"
      - name: Run Tests
        run: |
          python manage.py test
        env:
          ALLOWED_HOSTS: "*"
          MEDIA_PATH: ./media/
          STATIC_PATH: ./static/
          DJANGO_SETTINGS_MODULE: pipit.settings.test
          SECRET_KEY: some-test-key-not-good-for-prod
